"""
crew.py – Main orchestrator for the AI Data Analyst multi-agent pipeline.

Wires up the four CrewAI agents (profiler → analyst → coder → reporter)
into a sequential crew, executes the generated code against the user's
DataFrame, and returns a structured results dictionary.
"""

from __future__ import annotations

import os
import traceback
from typing import Any, Dict

import pandas as pd
from crewai import Crew, Process

from .profiler import create_profiler_agent, create_profile_task
from .analyst import create_analyst_agent, create_analysis_task
from .coder import create_coder_agent, create_code_task
from .reporter import create_reporter_agent, create_report_task

from utils.helpers import extract_code_from_text
from engine.executor import execute_code


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_data_summary(df: pd.DataFrame) -> str:
    """Create a textual summary of the DataFrame for the profiler agent.

    Includes shape, column names, dtypes, null counts, descriptive
    statistics, and the first five rows.
    """
    parts: list[str] = []

    parts.append(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns\n")

    parts.append(f"Columns: {', '.join(df.columns.tolist())}\n")

    parts.append("Data Types:\n" + df.dtypes.to_string() + "\n")

    parts.append(
        "Null Counts:\n" + df.isnull().sum().to_string() + "\n"
    )

    parts.append(
        "Descriptive Statistics:\n" + df.describe(include="all").to_string() + "\n"
    )

    parts.append(
        "First 5 Rows:\n" + df.head().to_string() + "\n"
    )

    return "\n".join(parts)


def _columns_info(df: pd.DataFrame) -> str:
    """Return a compact columns + dtypes string for the coder."""
    return "\n".join(
        f"- {col} ({dtype})" for col, dtype in zip(df.columns, df.dtypes)
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_analysis(df: pd.DataFrame, question: str, api_key: str) -> Dict[str, Any]:
    """Run the full multi-agent analysis pipeline.

    Parameters
    ----------
    df : pd.DataFrame
        The user's active dataset.
    question : str
        The natural-language question to answer.
    api_key : str
        OpenRouter API key (also set as OPENAI_API_KEY for LiteLLM).

    Returns
    -------
    dict
        Keys: ``profile``, ``plan``, ``code``, ``execution_result``,
        ``report``, ``success``.  On failure the dict also contains
        ``error``.
    """

    # ---- configure API keys for CrewAI / LiteLLM ----
    os.environ["OPENROUTER_API_KEY"] = api_key
    os.environ["OPENAI_API_KEY"] = api_key

    try:
        # ---- build data summary ----
        data_summary = _build_data_summary(df)
        col_info = _columns_info(df)

        # ---- create agents ----
        profiler_agent = create_profiler_agent(api_key=api_key)
        analyst_agent = create_analyst_agent(api_key=api_key)
        coder_agent = create_coder_agent(api_key=api_key)
        reporter_agent = create_reporter_agent(api_key=api_key)

        # ---- create tasks (chained via context) ----
        profile_task = create_profile_task(profiler_agent, data_summary)

        analysis_task = create_analysis_task(
            analyst_agent, question, data_summary,
        )
        analysis_task.context = [profile_task]

        # Instruct the coder to refer to the plan generated by the analyst
        code_plan_prompt = (
            f"Refer to the analysis plan generated in the previous step to answer "
            f"this question: {question}"
        )
        code_task = create_code_task(coder_agent, code_plan_prompt, col_info)
        code_task.context = [profile_task, analysis_task]

        # ---- assemble and run the analysis crew (profiler -> analyst -> coder) ----
        analysis_crew = Crew(
            agents=[profiler_agent, analyst_agent, coder_agent],
            tasks=[profile_task, analysis_task, code_task],
            process=Process.sequential,
            verbose=True,
        )

        analysis_crew.kickoff()

        # ---- extract individual task outputs ----
        profile_result = profile_task.output.raw if profile_task.output else ""
        plan_result = analysis_task.output.raw if analysis_task.output else ""
        code_raw = code_task.output.raw if code_task.output else ""

        # ---- extract and execute code ----
        code = extract_code_from_text(code_raw)
        execution_result: Dict[str, Any] = {"type": "text", "data": "No code generated."}

        if code.strip():
            execution_result = execute_code(df, code)

        # ---- format result summary for the reporter ----
        result_type = execution_result.get("type", "text")
        result_data = execution_result.get("data", "")

        if result_type == "dataframe":
            if isinstance(result_data, pd.DataFrame):
                summary_text = (
                    f"The code ran successfully and returned a DataFrame of shape {result_data.shape}.\n"
                    f"First 10 rows:\n{result_data.head(10).to_string()}\n"
                )
            else:
                summary_text = f"The code ran successfully and returned a DataFrame: {result_data}"
        elif result_type == "image":
            summary_text = (
                f"The code ran successfully and generated a visualization chart (saved as an image at: {result_data})."
            )
        elif result_type == "error":
            summary_text = (
                f"The code failed to execute and raised an exception:\n{result_data}\n"
            )
        else:
            summary_text = f"The code ran successfully and returned the following output:\n{result_data}"

        # ---- create and run the reporter crew with actual results ----
        report_task = create_report_task(
            reporter_agent, question, code, summary_text
        )
        report_task.context = [profile_task, analysis_task]

        reporter_crew = Crew(
            agents=[reporter_agent],
            tasks=[report_task],
            process=Process.sequential,
            verbose=True,
        )

        reporter_crew.kickoff()
        report_result = report_task.output.raw if report_task.output else ""

        return {
            "profile": profile_result,
            "plan": plan_result,
            "code": code,
            "execution_result": execution_result,
            "report": report_result,
            "success": True,
        }

    except Exception as exc:
        return {
            "profile": "",
            "plan": "",
            "code": "",
            "execution_result": {"type": "error", "data": str(exc)},
            "report": "",
            "success": False,
            "error": f"{type(exc).__name__}: {exc}\n{traceback.format_exc()}",
        }
